//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BazaarOfferItemTerm
    {
        public long Id { get; set; }
        public long BazaarOfferId { get; set; }
        public long ItemId { get; set; }
        public long Quantity { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual BazaarOffer BazaarOffer { get; set; }
    }
}
