//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class brigade
    {
        public brigade()
        {
            this.brigade_familiars = new HashSet<brigade_familiars>();
            this.raid_boss_brigade_attacks = new HashSet<raid_boss_brigade_attacks>();
        }
    
        public long id { get; set; }
        public long brigade_formation_id { get; set; }
        public Nullable<long> player_id { get; set; }
        public string name { get; set; }
        public string notes { get; set; }
    
        public virtual ICollection<brigade_familiars> brigade_familiars { get; set; }
        public virtual brigade_formations brigade_formations { get; set; }
        public virtual player player { get; set; }
        public virtual ICollection<raid_boss_brigade_attacks> raid_boss_brigade_attacks { get; set; }
    }
}
