//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrigadeFamiliarType
    {
        public long Id { get; set; }
        public long BrigadeId { get; set; }
        public long FamiliarTypeId { get; set; }
        public long BrigadeFormationPositionId { get; set; }
        public byte IsReserve { get; set; }
    
        public virtual BrigadeFormationPosition BrigadeFormationPosition { get; set; }
        public virtual FamiliarType FamiliarType { get; set; }
        public virtual Brigade Brigade { get; set; }
    }
}
