//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class brigade_formation_horizontal_position_types
    {
        public brigade_formation_horizontal_position_types()
        {
            this.brigade_formation_positions = new HashSet<brigade_formation_positions>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<brigade_formation_positions> brigade_formation_positions { get; set; }
    }
}
