//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrigadeFormationPosition
    {
        public BrigadeFormationPosition()
        {
            this.Familiars = new HashSet<BrigadeFamiliars>();
        }
    
        public long Id { get; set; }
        public long BrigadeFormationId { get; set; }
        public long HorizontalPositionTypeId { get; set; }
        public long VerticalPositionTypeId { get; set; }
    
        public virtual ICollection<BrigadeFamiliars> Familiars { get; set; }
        public virtual BrigadeFormationHorizontalPositionType HorizontalPositionTypes { get; set; }
        public virtual BrigadeFormationVerticalPositionType VerticalPositionTypes { get; set; }
        public virtual BrigadeFormation Formation { get; set; }
    }
}
