//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrigadeFamiliars
    {
        public long Id { get; set; }
        public long BrigadeId { get; set; }
        public long FamiliarId { get; set; }
        public long BrigadeFormationPositionId { get; set; }
        public byte IsReserve { get; set; }
    
        public virtual BrigadeFormationPositions BrigadeFormationPosition { get; set; }
        public virtual Familiar Familiar { get; set; }
        public virtual Brigade Brigade { get; set; }
    }
}
