//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrigadeFormation
    {
        public BrigadeFormation()
        {
            this.Positions = new HashSet<BrigadeFormationPosition>();
            this.Brigades = new HashSet<Brigade>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long NumPositions { get; set; }
    
        public virtual ICollection<BrigadeFormationPosition> Positions { get; set; }
        public virtual ICollection<Brigade> Brigades { get; set; }
    }
}
