//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class brigade_familiars
    {
        public long id { get; set; }
        public long brigade_id { get; set; }
        public long familiar_id { get; set; }
        public long brigade_formation_position_id { get; set; }
        public byte is_reserve { get; set; }
    
        public virtual brigade_formation_positions brigade_formation_positions { get; set; }
        public virtual familiar familiar { get; set; }
        public virtual brigade brigade { get; set; }
    }
}
