//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class brigade_formation_positions
    {
        public brigade_formation_positions()
        {
            this.brigade_familiars = new HashSet<brigade_familiars>();
        }
    
        public long id { get; set; }
        public long brigade_formation_id { get; set; }
        public long horizontal_position_type_id { get; set; }
        public long vertical_position_type_id { get; set; }
    
        public virtual ICollection<brigade_familiars> brigade_familiars { get; set; }
        public virtual brigade_formation_horizontal_position_types brigade_formation_horizontal_position_types { get; set; }
        public virtual brigade_formation_vertical_position_types brigade_formation_vertical_position_types { get; set; }
        public virtual brigade_formations brigade_formations { get; set; }
    }
}
