//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrigadeFormationHorizontalPositionType
    {
        public BrigadeFormationHorizontalPositionType()
        {
            this.BrigadeFormationPositions = new HashSet<BrigadeFormationPosition>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<BrigadeFormationPosition> BrigadeFormationPositions { get; set; }
    }
}
