//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public Event()
        {
            this.EliteFamiliarTypes = new HashSet<EventEliteFamiliarType>();
            this.RaidBossFamiliarTypes = new HashSet<RaidBossFamiliarTypes>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public long EventTypeId { get; set; }
        public string DateStarted { get; set; }
        public string DateEnded { get; set; }
    
        public virtual ICollection<EventEliteFamiliarType> EliteFamiliarTypes { get; set; }
        public virtual EventType Type { get; set; }
        public virtual ICollection<RaidBossFamiliarTypes> RaidBossFamiliarTypes { get; set; }
    }
}
