//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class familiar_types
    {
        public familiar_types()
        {
            this.bazaar_offer_familiar_type_terms = new HashSet<bazaar_offer_familiar_type_terms>();
            this.event_elite_familiar_types = new HashSet<event_elite_familiar_types>();
            this.familiar_type_skills = new HashSet<familiar_type_skills>();
            this.familiar_types1 = new HashSet<familiar_types>();
            this.familiar_types11 = new HashSet<familiar_types>();
            this.familiars = new HashSet<familiar>();
            this.raid_boss_familiar_types = new HashSet<raid_boss_familiar_types>();
        }
    
        public long id { get; set; }
        public Nullable<long> bb_id { get; set; }
        public string name { get; set; }
        public long rarity_id { get; set; }
        public short num_stars { get; set; }
        public short max_stars { get; set; }
        public long growth_id { get; set; }
        public long worth { get; set; }
        public long race_id { get; set; }
        public short tradable { get; set; }
        public string last_words { get; set; }
        public Nullable<long> prev_evolution_id { get; set; }
        public Nullable<long> next_evolution_id { get; set; }
    
        public virtual ICollection<bazaar_offer_familiar_type_terms> bazaar_offer_familiar_type_terms { get; set; }
        public virtual ICollection<event_elite_familiar_types> event_elite_familiar_types { get; set; }
        public virtual ICollection<familiar_type_skills> familiar_type_skills { get; set; }
        public virtual ICollection<familiar_types> familiar_types1 { get; set; }
        public virtual familiar_types familiar_types2 { get; set; }
        public virtual ICollection<familiar_types> familiar_types11 { get; set; }
        public virtual familiar_types familiar_types3 { get; set; }
        public virtual race race { get; set; }
        public virtual growth growth { get; set; }
        public virtual rarity rarity { get; set; }
        public virtual ICollection<familiar> familiars { get; set; }
        public virtual ICollection<raid_boss_familiar_types> raid_boss_familiar_types { get; set; }
    }
}
