//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Familiar
    {
        public Familiar()
        {
            this.BazaarOffers = new HashSet<bazaar_offers>();
            this.Brigades = new HashSet<BrigadeFamiliars>();
            this.Skills = new HashSet<familiar_skills>();
            this.SeedParents = new HashSet<Familiar>();
            this.SpawnParents = new HashSet<Familiar>();
        }
    
        public long Id { get; set; }
        public Nullable<long> PlayerId { get; set; }
        public long FamiliarTypeId { get; set; }
        public byte Owned { get; set; }
        public Nullable<double> Level { get; set; }
        public Nullable<double> HP { get; set; }
        public Nullable<double> ATK { get; set; }
        public Nullable<double> DEF { get; set; }
        public Nullable<double> WIS { get; set; }
        public Nullable<double> AGI { get; set; }
        public Nullable<double> EXP { get; set; }
        public long HPCrystals { get; set; }
        public long ATKCrystals { get; set; }
        public long DEFCrystals { get; set; }
        public long WISCrystals { get; set; }
        public long AGICrystals { get; set; }
        public Nullable<long> RootsCrystals { get; set; }
        public Nullable<long> SpawnParentId { get; set; }
        public Nullable<long> SeedParentId { get; set; }
    
        public virtual ICollection<bazaar_offers> BazaarOffers { get; set; }
        public virtual ICollection<BrigadeFamiliars> Brigades { get; set; }
        public virtual ICollection<familiar_skills> Skills { get; set; }
        public virtual FamiliarType FamiliarType { get; set; }
        public virtual Player Player { get; set; }
        public virtual ICollection<Familiar> SeedParents { get; set; }
        public virtual Familiar SeedParent { get; set; }
        public virtual ICollection<Familiar> SpawnParents { get; set; }
        public virtual Familiar SpawnParent { get; set; }
    }
}
