//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliarTypeStatValue
    {
        public long Id { get; set; }
        public long FamiliarTypeId { get; set; }
        public long StatTypeId { get; set; }
        public long StatId { get; set; }
        public double StatValue { get; set; }
    
        public virtual Stat Stat { get; set; }
        public virtual StatType StatType { get; set; }
        public virtual FamiliarType FamiliarTypes { get; set; }
    }
}
