//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class familiar
    {
        public familiar()
        {
            this.bazaar_offers = new HashSet<bazaar_offers>();
            this.brigade_familiars = new HashSet<brigade_familiars>();
            this.familiar_skills = new HashSet<familiar_skills>();
        }
    
        public long id { get; set; }
        public Nullable<long> player_id { get; set; }
        public long familiar_type_id { get; set; }
        public byte owned { get; set; }
        public Nullable<double> level { get; set; }
        public Nullable<double> hp { get; set; }
        public Nullable<double> atk { get; set; }
        public Nullable<double> def { get; set; }
        public Nullable<double> wis { get; set; }
        public Nullable<double> agi { get; set; }
        public Nullable<double> exp { get; set; }
        public long hp_crystals { get; set; }
        public long atk_crystals { get; set; }
        public long def_crystals { get; set; }
        public long wis_crystals { get; set; }
        public long agi_crystals { get; set; }
        public Nullable<long> roots_crystals { get; set; }
    
        public virtual ICollection<bazaar_offers> bazaar_offers { get; set; }
        public virtual ICollection<brigade_familiars> brigade_familiars { get; set; }
        public virtual ICollection<familiar_skills> familiar_skills { get; set; }
        public virtual familiar_types familiar_types { get; set; }
        public virtual player player { get; set; }
    }
}
