//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamiliarSkill
    {
        public long Id { get; set; }
        public long FamiliarId { get; set; }
        public long SkillId { get; set; }
        public short Level { get; set; }
        public short EXP { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual Familiar Familiar { get; set; }
    }
}
