//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public long Id { get; set; }
        public long ItemTypeId { get; set; }
        public Nullable<long> PlayerId { get; set; }
        public short QuantityTradable { get; set; }
        public short QuantityBloodbound { get; set; }
    
        public virtual ItemType ItemType { get; set; }
        public virtual Player Player { get; set; }
    }
}
