//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PhlebotomistModelContainer : DbContext
    {
        public PhlebotomistModelContainer()
            : base("name=PhlebotomistModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AttackType> AttackTypes { get; set; }
        public DbSet<BazaarOfferFamiliarTypeTerm> BazaarOfferFamiliarTypeTerms { get; set; }
        public DbSet<BazaarOfferItemTerm> BazaarOfferItemTerms1 { get; set; }
        public DbSet<BazaarOffer> BazaarOffers1 { get; set; }
        public DbSet<BrigadeFamiliars> BrigadeFamiliars { get; set; }
        public DbSet<BrigadeFormationHorizontalPositionType> BrigadeFormationHorizontalPositionTypes1 { get; set; }
        public DbSet<BrigadeFormationPosition> BrigadeFormationPositions1 { get; set; }
        public DbSet<BrigadeFormationVerticalPositionType> BrigadeFormationVerticalPositionTypes1 { get; set; }
        public DbSet<BrigadeFormation> BrigadeFormations1 { get; set; }
        public DbSet<Brigade> Brigades { get; set; }
        public DbSet<EventEliteFamiliarType> EventEliteFamiliarTypes1 { get; set; }
        public DbSet<EventType> EventTypes { get; set; }
        public DbSet<Event> Events1 { get; set; }
        public DbSet<FamiliarSkill> FamiliarSkills { get; set; }
        public DbSet<FamiliarTypeSkill> FamiliarTypeSkills { get; set; }
        public DbSet<FamiliarType> FamiliarTypes { get; set; }
        public DbSet<Familiar> Familiars { get; set; }
        public DbSet<Growth> Growths { get; set; }
        public DbSet<ItemType> ItemTypes1 { get; set; }
        public DbSet<Item> Items { get; set; }
        public DbSet<Player> Players { get; set; }
        public DbSet<Race> Races { get; set; }
        public DbSet<RaidBossBrigadeAttacks> RaidBossBrigadeAttacks { get; set; }
        public DbSet<RaidBossFamiliarTypes> RaidBossFamiliarTypes { get; set; }
        public DbSet<RaidBossType> RaidBossTypes1 { get; set; }
        public DbSet<RaidBoss> RaidBosses { get; set; }
        public DbSet<Rarity> Rarities1 { get; set; }
        public DbSet<SkillAffectedStat> SkillAffectedStats { get; set; }
        public DbSet<SkillPattern> SkillPatterns1 { get; set; }
        public DbSet<SkillTypes> SkillTypes { get; set; }
        public DbSet<Skill> Skills { get; set; }
        public DbSet<Stat> Stats { get; set; }
        public DbSet<familiar_type_stat_values> familiar_type_stat_values { get; set; }
        public DbSet<stat_types> stat_types { get; set; }
    }
}
