//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public Player()
        {
            this.Brigades = new HashSet<brigade>();
            this.Familiars = new HashSet<Familiar>();
            this.Items = new HashSet<item>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual ICollection<brigade> Brigades { get; set; }
        public virtual ICollection<Familiar> Familiars { get; set; }
        public virtual ICollection<item> Items { get; set; }
    }
}
