//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class player
    {
        public player()
        {
            this.brigades = new HashSet<brigade>();
            this.familiars = new HashSet<familiar>();
            this.items = new HashSet<item>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string created_date { get; set; }
    
        public virtual ICollection<brigade> brigades { get; set; }
        public virtual ICollection<familiar> familiars { get; set; }
        public virtual ICollection<item> items { get; set; }
    }
}
