//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaidBossBrigadeAttacks
    {
        public long Id { get; set; }
        public long RaidBossId { get; set; }
        public Nullable<long> BrigadeId { get; set; }
        public string Date { get; set; }
        public long AttackTypeId { get; set; }
        public Nullable<double> StartingHP { get; set; }
        public Nullable<double> EndingHP { get; set; }
        public Nullable<double> Damage { get; set; }
    
        public virtual AttackType AttackType { get; set; }
        public virtual Brigade Brigade { get; set; }
        public virtual RaidBoss RaidBoss { get; set; }
    }
}
