//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class raid_bosses
    {
        public raid_bosses()
        {
            this.raid_boss_brigade_attacks = new HashSet<raid_boss_brigade_attacks>();
        }
    
        public long id { get; set; }
        public long raid_boss_familiar_type { get; set; }
        public double level { get; set; }
        public Nullable<double> HP { get; set; }
        public Nullable<double> attack_points { get; set; }
        public Nullable<double> mvp_bonus_multiplier { get; set; }
        public Nullable<double> jur_mvp_bonus_multiplier { get; set; }
    
        public virtual ICollection<raid_boss_brigade_attacks> raid_boss_brigade_attacks { get; set; }
    }
}
