//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RaidBoss
    {
        public RaidBoss()
        {
            this.RaidBossBrigadeAttacks = new HashSet<RaidBossBrigadeAttacks>();
        }
    
        public long Id { get; set; }
        public long RaidBossFamiliarType { get; set; }
        public double Level { get; set; }
        public Nullable<double> HP { get; set; }
        public Nullable<double> AttackPoints { get; set; }
        public Nullable<double> MvpBonusMultiplier { get; set; }
        public Nullable<double> JurMvpBonusMultiplier { get; set; }
    
        public virtual ICollection<RaidBossBrigadeAttacks> RaidBossBrigadeAttacks { get; set; }
    }
}
