//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.Familiars = new HashSet<FamiliarSkill>();
            this.FamiliarTypes = new HashSet<FamiliarTypeSkill>();
            this.AffectedStats = new HashSet<SkillAffectedStat>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public long SkillTypeId { get; set; }
        public double MinProbability { get; set; }
        public double MaxProbability { get; set; }
        public Nullable<double> Modifier { get; set; }
        public Nullable<long> ModifierStatId { get; set; }
        public Nullable<byte> FlatModifier { get; set; }
        public Nullable<short> NumTargets { get; set; }
        public Nullable<long> SkillPatternId { get; set; }
        public Nullable<int> RowsRange { get; set; }
        public Nullable<int> ColumnsRange { get; set; }
        public string SkillBased { get; set; }
        public string DamageReduction { get; set; }
        public Nullable<long> FoeDefensiveModifierStatId { get; set; }
        public string Ability { get; set; }
        public Nullable<byte> IgnoresPosition { get; set; }
    
        public virtual ICollection<FamiliarSkill> Familiars { get; set; }
        public virtual ICollection<FamiliarTypeSkill> FamiliarTypes { get; set; }
        public virtual ICollection<SkillAffectedStat> AffectedStats { get; set; }
        public virtual SkillPattern Pattern { get; set; }
        public virtual SkillTypes Type { get; set; }
        public virtual Stat FoeDefensiveModifierStat { get; set; }
        public virtual Stat ModifierStat { get; set; }
    }
}
