//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SkillAffectedStat
    {
        public long Id { get; set; }
        public long SkillId { get; set; }
        public long StatId { get; set; }
        public Nullable<byte> Rank { get; set; }
        public byte AffectsAllies { get; set; }
        public byte AffectsFoes { get; set; }
    
        public virtual Stat Stat { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
