//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill
    {
        public skill()
        {
            this.familiar_skills = new HashSet<familiar_skills>();
            this.familiar_type_skills = new HashSet<familiar_type_skills>();
            this.skill_affected_stats = new HashSet<skill_affected_stats>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public long skill_type_id { get; set; }
        public double min_probability { get; set; }
        public double max_probability { get; set; }
        public Nullable<double> modifier { get; set; }
        public Nullable<long> modifier_stat_id { get; set; }
        public Nullable<byte> flat_modifier { get; set; }
        public Nullable<short> num_targets { get; set; }
        public Nullable<long> skill_pattern_id { get; set; }
        public Nullable<int> rows_range { get; set; }
        public Nullable<int> columns_range { get; set; }
        public string skill_based { get; set; }
        public string damage_reduction { get; set; }
        public Nullable<long> foe_defensive_modifier_stat_id { get; set; }
        public string ability { get; set; }
        public Nullable<byte> ignores_position { get; set; }
    
        public virtual ICollection<familiar_skills> familiar_skills { get; set; }
        public virtual ICollection<familiar_type_skills> familiar_type_skills { get; set; }
        public virtual ICollection<skill_affected_stats> skill_affected_stats { get; set; }
        public virtual skill_patterns skill_patterns { get; set; }
        public virtual skill_types skill_types { get; set; }
        public virtual stat stat { get; set; }
        public virtual stat stat1 { get; set; }
    }
}
