//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat
    {
        public stat()
        {
            this.skill_affected_stats = new HashSet<skill_affected_stats>();
            this.skills = new HashSet<skill>();
            this.skills1 = new HashSet<skill>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<skill_affected_stats> skill_affected_stats { get; set; }
        public virtual ICollection<skill> skills { get; set; }
        public virtual ICollection<skill> skills1 { get; set; }
    }
}
