//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stat_types
    {
        public stat_types()
        {
            this.familiar_type_stat_values = new HashSet<familiar_type_stat_values>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<familiar_type_stat_values> familiar_type_stat_values { get; set; }
    }
}
