//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class attack_types
    {
        public attack_types()
        {
            this.raid_boss_brigade_attacks = new HashSet<raid_boss_brigade_attacks>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<raid_boss_brigade_attacks> raid_boss_brigade_attacks { get; set; }
    }
}
