//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item_types
    {
        public item_types()
        {
            this.bazaar_offer_item_terms = new HashSet<bazaar_offer_item_terms>();
            this.items = new HashSet<item>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string description { get; set; }
    
        public virtual ICollection<bazaar_offer_item_terms> bazaar_offer_item_terms { get; set; }
        public virtual ICollection<item> items { get; set; }
    }
}
