//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public long id { get; set; }
        public long item_type_id { get; set; }
        public Nullable<long> player_id { get; set; }
        public short quantity_tradable { get; set; }
        public short quantity_bloodbound { get; set; }
    
        public virtual item_types item_types { get; set; }
        public virtual player player { get; set; }
    }
}
