//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class raid_boss_brigade_attacks
    {
        public long id { get; set; }
        public long raid_boss_id { get; set; }
        public Nullable<long> brigade_id { get; set; }
        public string date { get; set; }
        public long attack_type_id { get; set; }
        public Nullable<double> starting_HP { get; set; }
        public Nullable<double> ending_HP { get; set; }
        public Nullable<double> damage { get; set; }
    
        public virtual attack_types attack_types { get; set; }
        public virtual brigade brigade { get; set; }
        public virtual raid_bosses raid_bosses { get; set; }
    }
}
