//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phlebotomist.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class skill_affected_stats
    {
        public long id { get; set; }
        public long skill_id { get; set; }
        public long stat_id { get; set; }
        public Nullable<byte> rank { get; set; }
        public byte affects_allies { get; set; }
        public byte affects_foes { get; set; }
    
        public virtual stat stat { get; set; }
        public virtual skill skill { get; set; }
    }
}
